trigger: { branches: { include: [ main ] } }
pr:       { branches: { include: [ main ] } }

variables:
  # 镜像（api）
  apiRepo: 'docker.io/rayrayye/timeapp-api-new'
  dockerfilePath: 'Dockerfile'
  buildContext: '.'

  # 配置仓（GitHub）
  githubOrgRepo: 'RookieToExpert/az305'
  configPath: 'kubernetes&docker/timeapp-config/overlays/prod'
  configBranchPrefix: 'bump-api'

  # 版本号（与 web 解耦的计数器）
  major: '1'
  counterKey: 'api-1'
  patch: $[ counter(variables['counterKey'], 0) ]
  version: '$(major).$(patch)'

stages:
- stage: Build
  displayName: Build & Push (api)
  jobs:
  - job: build
    pool: { vmImage: 'ubuntu-latest' }
    steps:
    - task: Docker@2
      displayName: Login Docker Hub
      inputs: { command: login, containerRegistry: 'toDockerHub' }

    - task: Docker@2
      displayName: Build+Push api:$(version)
      inputs:
        command: buildAndPush
        repository: '$(apiRepo)'
        Dockerfile: '$(dockerfilePath)'
        buildContext: '$(buildContext)'
        tags: |
          $(version)

- stage: ConfigPR
  displayName: 'Create PR to bump api tag (GitOps)'
  dependsOn: Build
  jobs:
  - job: pr
    pool: { vmImage: 'ubuntu-latest' }
    steps:
    - script: |
        set -eux
        curl -L https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64 -o /usr/local/bin/yq
        chmod +x /usr/local/bin/yq
        sudo apt-get update && sudo apt-get install -y gh
      displayName: Install yq & gh

    - script: |
        set -eux
        export GH_TOKEN="$(GITHUB_TOKEN)"
        git config --global user.name  "ado-bot"
        git config --global user.email "ado-bot@example.com"

        git clone "https://github.com/$(githubOrgRepo).git" configrepo
        cd configrepo

        BR="$(configBranchPrefix)-$(version)-$(Build.BuildId)"
        git checkout -b "$BR"

        FILE="$(configPath)/kustomization.yaml"
        export IMG_NAME="$(apiRepo)"
        export VERSION="$(version)"
        yq -i '(.images[] | select(.name == env(IMG_NAME))).newTag = env(VERSION)' "$FILE"

        echo "After change:" && yq '.images' "$FILE"

        git add "$FILE"
        git commit -m "chore(api): bump to $(version)"
        git push -u origin "$BR"

        gh pr create \
          --repo "$(githubOrgRepo)" \
          --base main --head "$BR" \
          --title "Bump api to $(version)" \
          --body "Update api image tag to $(version) for GitOps" \
          --label "gitops"
      displayName: Bump api tag & open PR
      env:
        GITHUB_TOKEN: $(GITHUB_TOKEN)
